### PR TITLE
Arrays of Java classes and multi-dimensional arrays. Bug 2758.

### PR DESCRIPTION
**Pull request by adamburkegh**
Should preferably wait for merge of https://github.com/jython/book/pull/4 and tag of 1.0 version.

### CODE REVIEW

**Comment by jeff5** [comment]
Thanks, this is a good addition. It's quite acceptable as is, but I wondered about writing, just to drive the point home:
```
>>> ci = Class.forName('[I') # Name of an array of Java int
>>> a = array([[1,2,3],[4,5,6,7,8]],ci)
>>> a[1][3]
7
```
And `ci` is not a very suggestive name. `ai` maybe, or `AI` (it's a class after all)? I want to say `AAI`, but of course this is the *element* type, not the whole array type.

Works for me on 2.5.3 and 2.7.2a1.

**Comment by adamburkegh** [comment]
Hi @jeff5 , incorporated your suggestion, makes sense to me.

**Comment by jeff5** [comment]
Looks good to me. Thanks Adam.

Hmm. I see I made the title too long. I'll get the hang of squash commits eventually.

**Comment by adamburkegh** [comment]
Cheers : )

**Pull request merged**
